//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public Object()
        {
            this.Comments = new HashSet<Comment>();
            this.Categories = new HashSet<Category>();
            this.Users = new HashSet<User>();
            this.Collections = new HashSet<Collection>();
            this.Marks = new HashSet<Mark>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<double> AvarageMark { get; set; }
        public System.DateTime CreatingDate { get; set; }
    
        public virtual File File { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Collection> Collections { get; set; }
        public virtual ICollection<Mark> Marks { get; set; }
    }
}
