//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Objects = new HashSet<Object>();
            this.Collections = new HashSet<Collection>();
            this.Marks = new HashSet<Mark>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Object> Objects { get; set; }
        public virtual ICollection<Collection> Collections { get; set; }
        public virtual ICollection<Mark> Marks { get; set; }
    }
}
